### ISSUE TITLE
speech_commands/generate_commands.py errors with Multinet + fix

### ISSUE THREAD

**Issue by RJ** [toverainc/willow#47]
(i flashed and tested sucessfully without multinet btw)

Enabled multinet in config, and running build errors like so:

```
root@770980441ff8:/willow# ./utils.sh build
MULTINET: Generate speech commands: Attempting to fetch your ['light.', 'switch.'] entities from Home Assistant...
Traceback (most recent call last):
  File "speech_commands/generate_commands.py", line 84, in <module>
    numbers = re.search(r'(\d{1,})', friendly_name)
  File "/usr/lib/python3.8/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
root@770980441ff8:/willow#
```

It's because I get a rogue`friendly_name` = `None` back from home assistant. maybe a HA config issue or something. 

to make it more robust i just skip entities with a None friendy_name:

```diff
(base) rj@rjms:~/src/willow$ git diff
diff --git a/speech_commands/generate_commands.py b/speech_commands/generate_commands.py
index 4fd9368..31fcb43 100644
--- a/speech_commands/generate_commands.py
+++ b/speech_commands/generate_commands.py
@@ -81,6 +81,9 @@ for type in entity_types:
         if entity_id.startswith(type):
             attr = entity.get('attributes')
             friendly_name = attr.get('friendly_name')
+            if friendly_name is None:
+                # in case of blank or misconfigured HA entities
+                continue
             numbers = re.search(r'(\d{1,})', friendly_name)
             if numbers:
                 for number in numbers.groups():
(base) rj@rjms:~/src/willow$ 
```

Great job btw, looking forward to playing around with this!

**Comment by RJ** [comment]
multinet local stuff is reassuringly fast ✅

https://github.com/toverainc/willow/assets/29747/7c796396-6b4e-400f-897d-24821f13f65e
